import:
  - ~/.config/alacritty/dracula.yml

font:
  normal:
    family: "Terminus"
  size: 10.5

env:
  TERM: alacritty

window:
  dimensions:
    columns: 82
    lines: 25

  padding:
    x: 10
    y: 10
  
  decorations: full
  startup_mode: Windowed
  dynamic_title: true

  history: 10000
  multiplier: 3

  background_opacity: 1.0

  cursor:
    style:
      shape: Black
      blinking: On

    unfocused_hollow: false

  live_config_reload: true    
