[general]
import = ["~/.config/alacritty/alacritty-theme/themes"]
live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
padding = { x = 2, y = 3 }

[scrolling]
history = 50000

[cursor]
style = {shape = "Beam", blinking = "On"}
